# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='key',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
