# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption', '0002_auto_20170214_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='text',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
