# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption', '0004_item_media_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linetrans',
            options={'ordering': ['line'], 'verbose_name_plural': 'Linetranslations'},
        ),
        migrations.AlterField(
            model_name='item',
            name='media_type',
            field=models.CharField(choices=[('ytb', 'youtube'), ('mp3', 'mp3')], max_length=3),
        ),
    ]
